# Generated by Django 3.0.3 on 2020-02-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lprice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sprice',
            field=models.FloatField(null=True),
        ),
    ]
