# Generated by Django 3.1.4 on 2020-12-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20210101_0008'),
        ('orders', '0005_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
